[package]
name = "rustfu-renderer"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
byteorder = "1.3.4"
euclid = "0.20.13"
image = { version = "0.23.6", default-features = false, features = [ "png" ] }
glow = { version = "0.5.0", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
std_web  = { version = "0.4", package = "stdweb" }
webgl_stdweb = { version = "0.3" }

[features]
stdweb = ["glow/stdweb"]
